title = "La Siorén’na"
baseURL = 'http://lasiorenna.it/'
languageCode = 'it-IT'
theme = 'ananke'
SectionPagesMenu = "main"
#Paginate = 9
googleAnalytics = "G-DD2J2SJ5ZS"
enableRobotsTXT = true

defaultContentLanguage = "it"
[languages]
    [languages.it]
        contentDir = "content/it"
        disabled = false
        languageCode = 'it-IT'
        languageName = 'Italian'
        weight = 1
    [languages.en]
        contentDir = 'content/en'
        disabled = false
        languageCode = 'en-US'
        languageName = 'English'
        weight = 2

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
body_classes = "baskerville bg-washed-yellow" #bg-washed-green"
text_color = ""
author = "Carlo Bocchi e Lucia Gozzi"
#site_logo = "logo.svg"
description = "Agriturismo Bed and Breakfast La Siorenna"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 2
#mainSections =

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/lasiorenna"

